name: CI

on:
  push:
    paths:
      - '**/*.cairo'
      - '**/*.toml'
  pull_request:
    paths:
      - '**/*.cairo'
      - '**/*.toml'

jobs:
  sozo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -L https://install.dojoengine.org | bash
      - run: /home/runner/.config/.dojo/bin/dojoup
      - run: /home/runner/.config/.dojo/bin/sozo test